### ISSUE TITLE
unclickable Days with event

### ISSUE THREAD

**Issue by amirahmadihr** [aminmokhtari94/vue-persian-calendar#27]
hi there, 
the event  on-day-click (as you said in doc) dont work.
please check and resolve the prob
ty

**Comment by d4rkr3pt0r** [comment]
@amirahmadihr As you may see in the source file, to activate `on-day-click` you should pass `:disablePastDays="true"` and clicked day shouldn't be before of the current day.
```
    emitDay(day, $event) {
      if (this.disablePastDays) {
        if (!day.isBefore(this.$moment(), 'day')) {
          this.$emit('on-day-click', day);
        } else {
          $event.stopPropagation();
        }
      }
    }
```

**Comment by amirahmadihr** [comment]
> @amirahmadihr As you may see in the source file, to activate `on-day-click` you should pass `:disablePastDays="true"` and clicked day shouldn't be before of the current day.
> 
> ```
>     emitDay(day, $event) {
>       if (this.disablePastDays) {
>         if (!day.isBefore(this.$moment(), 'day')) {
>           this.$emit('on-day-click', day);
>         } else {
>           $event.stopPropagation();
>         }
>       }
>     }
> ```
